#!/usr/bin/env node

/**
 * Build self-contained CJS bundles for the plugin distribution.
 *
 * Outputs:
 *   dist/plugin/worker-service.cjs   – Worker HTTP daemon (background process)
 *   dist/plugin/mcp-server.cjs       – MCP stdio server (launched per-session)
 *
 * These bundles can be deployed alongside the plugin/ config files so that
 * users don't need the full node_modules tree.
 *
 * Usage:
 *   node scripts/build-plugin.js            # production (minified)
 *   node scripts/build-plugin.js --dev      # development (no minify, sourcemaps)
 */

import { build } from 'esbuild';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, '..');
const isDev = process.argv.includes('--dev');

/** Packages that should stay as external requires (native addons, etc.) */
const externalPackages = [
  // pg uses optional native bindings — keep external so the user's
  // installed pg-native (if present) is picked up at runtime.
  'pg-native',
  // ONNX runtime has platform-specific .node binaries that can't be bundled.
  // The @huggingface/transformers package depends on these at runtime.
  'onnxruntime-node',
  'sharp',
];

/**
 * esbuild plugin to rewrite import.meta.* references for CJS output.
 * - import.meta.dirname  → __dirname
 * - import.meta.url      → "file://" + __filename
 * - import.meta.filename → __filename
 */
const importMetaPlugin = {
  name: 'import-meta-polyfill',
  setup(build) {
    build.onLoad({ filter: /\.[cm]?[jt]sx?$/ }, async (args) => {
      const fs = await import('node:fs');
      let contents = await fs.promises.readFile(args.path, 'utf8');

      // Only transform our source files, not node_modules
      if (args.path.includes('node_modules')) return undefined;

      contents = contents
        .replace(/\bimport\.meta\.dirname\b/g, '__dirname')
        .replace(/\bimport\.meta\.filename\b/g, '__filename')
        .replace(/\bimport\.meta\.url\b/g, '("file://" + __filename)');

      return { contents, loader: args.path.endsWith('.ts') ? 'ts' : 'js' };
    });
  },
};

/** Shared esbuild options */
const shared = {
  bundle: true,
  platform: 'node',
  target: 'node22',
  format: 'cjs',
  external: externalPackages,
  outdir: path.join(root, 'plugin', 'scripts'),
  minify: !isDev,
  sourcemap: isDev ? 'inline' : false,
  logLevel: 'warning',
  plugins: [importMetaPlugin],
  banner: {
    js: [
      '// Auto-generated by build-plugin.js — do not edit',
      '"use strict";',
    ].join('\n'),
  },
};

async function main() {
  console.log(`Building plugin bundles (${isDev ? 'dev' : 'production'})…`);

  const entries = [
    {
      entryPoints: [path.join(root, 'src', 'services', 'worker-service.ts')],
      outfile: path.join(root, 'plugin', 'scripts', 'worker-service.cjs'),
    },
    {
      entryPoints: [path.join(root, 'src', 'servers', 'mcp-server.ts')],
      outfile: path.join(root, 'plugin', 'scripts', 'mcp-server.cjs'),
    },
  ];

  const results = await Promise.all(
    entries.map(({ entryPoints, outfile }) =>
      build({
        ...shared,
        entryPoints,
        outfile,
        outdir: undefined, // outfile takes precedence
        // Mark @huggingface/transformers as external if you want to keep
        // the large ONNX runtime out of the bundle. Users then need
        // node_modules available. To fully self-contain, remove this line.
        // external: [...externalPackages, '@huggingface/transformers'],
      })
    )
  );

  const errors = results.flatMap((r) => r.errors);
  if (errors.length > 0) {
    console.error('Build failed with errors:');
    errors.forEach((e) => console.error(e));
    process.exit(1);
  }

  const warnings = results.flatMap((r) => r.warnings);
  if (warnings.length > 0) {
    console.warn(`Build completed with ${warnings.length} warning(s).`);
    warnings.forEach((w) => console.warn(w));
  }

  console.log('Plugin bundles written to plugin/scripts/');
  console.log('  - worker-service.cjs');
  console.log('  - mcp-server.cjs');
}

main().catch((err) => {
  console.error('Build script failed:', err);
  process.exit(1);
});
